// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRo8Mg81AUyoLY3gdfDo1rez7iFBrQ5WY',
    appId: '1:405088979256:web:550899d7085531a38399cd',
    messagingSenderId: '405088979256',
    projectId: 'facultyapp-15f6c',
    authDomain: 'facultyapp-15f6c.firebaseapp.com',
    storageBucket: 'facultyapp-15f6c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3CLcZ1Juswk4lmDlJU5OZxlHV0qsNArU',
    appId: '1:405088979256:android:0145062d5f4cbbdb8399cd',
    messagingSenderId: '405088979256',
    projectId: 'facultyapp-15f6c',
    storageBucket: 'facultyapp-15f6c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5oEXkmtYTMOhqPDCgWALCFgptResm2cE',
    appId: '1:405088979256:ios:d4e7d596b24d0a308399cd',
    messagingSenderId: '405088979256',
    projectId: 'facultyapp-15f6c',
    storageBucket: 'facultyapp-15f6c.appspot.com',
    iosClientId: '405088979256-p8fqvf21mk7k2s2no314v4nt0g460mg0.apps.googleusercontent.com',
    iosBundleId: 'com.example.facultyColloboration',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5oEXkmtYTMOhqPDCgWALCFgptResm2cE',
    appId: '1:405088979256:ios:84e63d4c2329c9fc8399cd',
    messagingSenderId: '405088979256',
    projectId: 'facultyapp-15f6c',
    storageBucket: 'facultyapp-15f6c.appspot.com',
    iosClientId: '405088979256-0uiko8guqlk80rgepc7piarkai2t65ag.apps.googleusercontent.com',
    iosBundleId: 'com.example.facultyColloboration.RunnerTests',
  );
}
